from pathlib import Path
from django.utils.text import slugify

TEAM_LOGOS = {
    ("MLB", "Arizona Diamondbacks"): "logos/tsdb/mlb/arizona-diamondbacks.png",
    ("MLB", "Athletics"): "logos/tsdb/mlb/athletics.png",
    ("MLB", "Atlanta Braves"): "logos/tsdb/mlb/atlanta-braves.png",
    ("MLB", "Baltimore Orioles"): "logos/tsdb/mlb/baltimore-orioles.png",
    ("MLB", "Boston Red Sox"): "logos/tsdb/mlb/boston-red-sox.png",
    ("MLB", "Chicago Cubs"): "logos/tsdb/mlb/chicago-cubs.png",
    ("MLB", "Chicago White Sox"): "logos/tsdb/mlb/chicago-white-sox.png",
    ("MLB", "Cincinnati Reds"): "logos/tsdb/mlb/cincinnati-reds.png",
    ("MLB", "Cleveland Guardians"): "logos/tsdb/mlb/cleveland-guardians.png",
    ("MLB", "Colorado Rockies"): "logos/tsdb/mlb/colorado-rockies.png",
    ("MLB", "Detroit Tigers"): "logos/tsdb/mlb/detroit-tigers.png",
    ("MLB", "Houston Astros"): "logos/tsdb/mlb/houston-astros.png",
    ("MLB", "Kansas City Royals"): "logos/tsdb/mlb/kansas-city-royals.png",
    ("MLB", "Los Angeles Angels"): "logos/tsdb/mlb/los-angeles-angels.png",
    ("MLB", "Los Angeles Dodgers"): "logos/tsdb/mlb/los-angeles-dodgers.png",
    ("MLB", "Miami Marlins"): "logos/tsdb/mlb/miami-marlins.png",
    ("MLB", "Milwaukee Brewers"): "logos/tsdb/mlb/milwaukee-brewers.png",
    ("MLB", "Minnesota Twins"): "logos/tsdb/mlb/minnesota-twins.png",
    ("MLB", "New York Mets"): "logos/tsdb/mlb/new-york-mets.png",
    ("MLB", "New York Yankees"): "logos/tsdb/mlb/new-york-yankees.png",
    ("MLB", "Philadelphia Phillies"): "logos/tsdb/mlb/philadelphia-phillies.png",
    ("MLB", "Pittsburgh Pirates"): "logos/tsdb/mlb/pittsburgh-pirates.png",
    ("MLB", "San Diego Padres"): "logos/tsdb/mlb/san-diego-padres.png",
    ("MLB", "San Francisco Giants"): "logos/tsdb/mlb/san-francisco-giants.png",
    ("MLB", "Seattle Mariners"): "logos/tsdb/mlb/seattle-mariners.png",
    ("MLB", "St. Louis Cardinals"): "logos/tsdb/mlb/st-louis-cardinals.png",
    ("MLB", "Tampa Bay Rays"): "logos/tsdb/mlb/tampa-bay-rays.png",
    ("MLB", "Texas Rangers"): "logos/tsdb/mlb/texas-rangers.png",
    ("MLB", "Toronto Blue Jays"): "logos/tsdb/mlb/toronto-blue-jays.png",
    ("MLB", "Washington Nationals"): "logos/tsdb/mlb/washington-nationals.png",


("NBA", "Atlanta Hawks"): "logos/tsdb/nba/atlanta-hawks.png",
("NBA", "Boston Celtics"): "logos/tsdb/nba/boston-celtics.png",
("NBA", "Brooklyn Nets"): "logos/tsdb/nba/brooklyn-nets.png",
("NBA", "Charlotte Hornets"): "logos/tsdb/nba/charlotte-hornets.png",
("NBA", "Chicago Bulls"): "logos/tsdb/nba/chicago-bulls.png",
("NBA", "Cleveland Cavaliers"): "logos/tsdb/nba/cleveland-cavaliers.png",
("NBA", "Dallas Mavericks"): "logos/tsdb/nba/dallas-mavericks.png",
("NBA", "Denver Nuggets"): "logos/tsdb/nba/denver-nuggets.png",
("NBA", "Detroit Pistons"): "logos/tsdb/nba/detroit-pistons.png",
("NBA", "Golden State Warriors"): "logos/tsdb/nba/golden-state-warriors.png",
("NBA", "Houston Rockets"): "logos/tsdb/nba/houston-rockets.png",
("NBA", "Indiana Pacers"): "logos/tsdb/nba/indiana-pacers.png",
("NBA", "Los Angeles Clippers"): "logos/tsdb/nba/los-angeles-clippers.png",
("NBA", "Los Angeles Lakers"): "logos/tsdb/nba/los-angeles-lakers.png",
("NBA", "Memphis Grizzlies"): "logos/tsdb/nba/memphis-grizzlies.png",
("NBA", "Miami Heat"): "logos/tsdb/nba/miami-heat.png",
("NBA", "Milwaukee Bucks"): "logos/tsdb/nba/milwaukee-bucks.png",
("NBA", "Minnesota Timberwolves"): "logos/tsdb/nba/minnesota-timberwolves.png",
("NBA", "New Orleans Pelicans"): "logos/tsdb/nba/new-orleans-pelicans.png",
("NBA", "New York Knicks"): "logos/tsdb/nba/new-york-knicks.png",
("NBA", "Oklahoma City Thunder"): "logos/tsdb/nba/oklahoma-city-thunder.png",
("NBA", "Orlando Magic"): "logos/tsdb/nba/orlando-magic.png",
("NBA", "Philadelphia 76ers"): "logos/tsdb/nba/philadelphia-76ers.png",
("NBA", "Phoenix Suns"): "logos/tsdb/nba/phoenix-suns.png",
("NBA", "Portland Trail Blazers"): "logos/tsdb/nba/portland-trail-blazers.png",
("NBA", "Sacramento Kings"): "logos/tsdb/nba/sacramento-kings.png",
("NBA", "San Antonio Spurs"): "logos/tsdb/nba/san-antonio-spurs.png",
("NBA", "Toronto Raptors"): "logos/tsdb/nba/toronto-raptors.png",
("NBA", "Utah Jazz"): "logos/tsdb/nba/utah-jazz.png",
("NBA", "Washington Wizards"): "logos/tsdb/nba/washington-wizards.png",


("NFL", "Arizona Cardinals"): "logos/tsdb/nfl/arizona-cardinals.png",
    ("NFL", "Atlanta Falcons"): "logos/tsdb/nfl/atlanta-falcons.png",
    ("NFL", "Baltimore Ravens"): "logos/tsdb/nfl/baltimore-ravens.png",
    ("NFL", "Buffalo Bills"): "logos/tsdb/nfl/buffalo-bills.png",
    ("NFL", "Carolina Panthers"): "logos/tsdb/nfl/carolina-panthers.png",
    ("NFL", "Chicago Bears"): "logos/tsdb/nfl/chicago-bears.png",
    ("NFL", "Cincinnati Bengals"): "logos/tsdb/nfl/cincinnati-bengals.png",
    ("NFL", "Cleveland Browns"): "logos/tsdb/nfl/cleveland-browns.png",
    ("NFL", "Dallas Cowboys"): "logos/tsdb/nfl/dallas-cowboys.png",
    ("NFL", "Denver Broncos"): "logos/tsdb/nfl/denver-broncos.png",
    ("NFL", "Detroit Lions"): "logos/tsdb/nfl/detroit-lions.png",
    ("NFL", "Green Bay Packers"): "logos/tsdb/nfl/green-bay-packers.png",
    ("NFL", "Houston Texans"): "logos/tsdb/nfl/houston-texans.png",
    ("NFL", "Indianapolis Colts"): "logos/tsdb/nfl/indianapolis-colts.png",
    ("NFL", "Jacksonville Jaguars"): "logos/tsdb/nfl/jacksonville-jaguars.png",
    ("NFL", "Kansas City Chiefs"): "logos/tsdb/nfl/kansas-city-chiefs.png",
    ("NFL", "Las Vegas Raiders"): "logos/tsdb/nfl/las-vegas-raiders.png",
    ("NFL", "Los Angeles Chargers"): "logos/tsdb/nfl/los-angeles-chargers.png",
    ("NFL", "Los Angeles Rams"): "logos/tsdb/nfl/los-angeles-rams.png",
    ("NFL", "Miami Dolphins"): "logos/tsdb/nfl/miami-dolphins.png",
    ("NFL", "Minnesota Vikings"): "logos/tsdb/nfl/minnesota-vikings.png",
    ("NFL", "New England Patriots"): "logos/tsdb/nfl/new-england-patriots.png",
    ("NFL", "New Orleans Saints"): "logos/tsdb/nfl/new-orleans-saints.png",
    ("NFL", "New York Giants"): "logos/tsdb/nfl/new-york-giants.png",
    ("NFL", "New York Jets"): "logos/tsdb/nfl/new-york-jets.png",
    ("NFL", "Philadelphia Eagles"): "logos/tsdb/nfl/philadelphia-eagles.png",
    ("NFL", "Pittsburgh Steelers"): "logos/tsdb/nfl/pittsburgh-steelers.png",
    ("NFL", "San Francisco 49ers"): "logos/tsdb/nfl/san-francisco-49ers.png",
    ("NFL", "Seattle Seahawks"): "logos/tsdb/nfl/seattle-seahawks.png",
    ("NFL", "Tampa Bay Buccaneers"): "logos/tsdb/nfl/tampa-bay-buccaneers.png",
    ("NFL", "Tennessee Titans"): "logos/tsdb/nfl/tennessee-titans.png",
    ("NFL", "Washington Commanders"): "logos/tsdb/nfl/washington-commanders.png",

    ("NFL", "ARI"): "logos/tsdb/nfl/arizona-cardinals.png",
    ("NFL", "ATL"): "logos/tsdb/nfl/atlanta-falcons.png",
    ("NFL", "BAL"): "logos/tsdb/nfl/baltimore-ravens.png",
    ("NFL", "BUF"): "logos/tsdb/nfl/buffalo-bills.png",
    ("NFL", "CAR"): "logos/tsdb/nfl/carolina-panthers.png",
    ("NFL", "CHI"): "logos/tsdb/nfl/chicago-bears.png",
    ("NFL", "CIN"): "logos/tsdb/nfl/cincinnati-bengals.png",
    ("NFL", "CLE"): "logos/tsdb/nfl/cleveland-browns.png",
    ("NFL", "DAL"): "logos/tsdb/nfl/dallas-cowboys.png",
    ("NFL", "DEN"): "logos/tsdb/nfl/denver-broncos.png",
    ("NFL", "DET"): "logos/tsdb/nfl/detroit-lions.png",
    ("NFL", "GB"): "logos/tsdb/nfl/green-bay-packers.png",
    ("NFL", "HOU"): "logos/tsdb/nfl/houston-texans.png",
    ("NFL", "IND"): "logos/tsdb/nfl/indianapolis-colts.png",
    ("NFL", "JAX"): "logos/tsdb/nfl/jacksonville-jaguars.png",
    ("NFL", "KC"): "logos/tsdb/nfl/kansas-city-chiefs.png",
    ("NFL", "LV"): "logos/tsdb/nfl/las-vegas-raiders.png",
    ("NFL", "LAC"): "logos/tsdb/nfl/los-angeles-chargers.png",
    ("NFL", "LAR"): "logos/tsdb/nfl/los-angeles-rams.png",
    ("NFL", "MIA"): "logos/tsdb/nfl/miami-dolphins.png",
    ("NFL", "MIN"): "logos/tsdb/nfl/minnesota-vikings.png",
    ("NFL", "NE"): "logos/tsdb/nfl/new-england-patriots.png",
    ("NFL", "NO"): "logos/tsdb/nfl/new-orleans-saints.png",
    ("NFL", "NYG"): "logos/tsdb/nfl/new-york-giants.png",
    ("NFL", "NYJ"): "logos/tsdb/nfl/new-york-jets.png",
    ("NFL", "PHI"): "logos/tsdb/nfl/philadelphia-eagles.png",
    ("NFL", "PIT"): "logos/tsdb/nfl/pittsburgh-steelers.png",
    ("NFL", "SF"): "logos/tsdb/nfl/san-francisco-49ers.png",
    ("NFL", "SEA"): "logos/tsdb/nfl/seattle-seahawks.png",
    ("NFL", "TB"): "logos/tsdb/nfl/tampa-bay-buccaneers.png",
    ("NFL", "TEN"): "logos/tsdb/nfl/tennessee-titans.png",
    ("NFL", "WAS"): "logos/tsdb/nfl/washington-commanders.png",

("WNBA", "Atlanta Dream"): "logos/wnba/atlanta-dream.svg",
("WNBA", "Chicago Sky"): "logos/wnba/chicago-sky.svg",
("WNBA", "Connecticut Sun"): "logos/wnba/connecticut-sun.svg",
("WNBA", "Dallas Wings"): "logos/wnba/dallas-wings.svg",
("WNBA", "Golden State Valkyries"): "logos/wnba/golden-state-valkyries.svg",
("WNBA", "Indiana Fever"): "logos/wnba/indiana-fever.svg",
("WNBA", "Las Vegas Aces"): "logos/wnba/las-vegas-aces.svg",
("WNBA", "Los Angeles Sparks"): "logos/wnba/los-angeles-sparks.svg",
("WNBA", "Minnesota Lynx"): "logos/wnba/minnesota-lynx.svg",
("WNBA", "New York Liberty"): "logos/wnba/new-york-liberty.svg",
("WNBA", "Phoenix Mercury"): "logos/wnba/phoenix-mercury.svg",
("WNBA", "Seattle Storm"): "logos/wnba/seattle-storm.svg",
("WNBA", "Washington Mystics"): "logos/wnba/washington-mystics.svg",

    # NHL

    ("NHL", "Anaheim Ducks"): "logos/tsdb/nhl/anaheim-ducks.png",
    ("NHL", "Boston Bruins"): "logos/tsdb/nhl/boston-bruins.png",
    ("NHL", "Buffalo Sabres"): "logos/tsdb/nhl/buffalo-sabres.png",
    ("NHL", "Calgary Flames"): "logos/tsdb/nhl/calgary-flames.png",
    ("NHL", "Carolina Hurricanes"): "logos/tsdb/nhl/carolina-hurricanes.png",
    ("NHL", "Chicago Blackhawks"): "logos/tsdb/nhl/chicago-blackhawks.png",
    ("NHL", "Colorado Avalanche"): "logos/tsdb/nhl/colorado-avalanche.png",
    ("NHL", "Columbus Blue Jackets"): "logos/tsdb/nhl/columbus-blue-jackets.png",
    ("NHL", "Dallas Stars"): "logos/tsdb/nhl/dallas-stars.png",
    ("NHL", "Detroit Red Wings"): "logos/tsdb/nhl/detroit-red-wings.png",
    ("NHL", "Edmonton Oilers"): "logos/tsdb/nhl/edmonton-oilers.png",
    ("NHL", "Florida Panthers"): "logos/tsdb/nhl/florida-panthers.png",
    ("NHL", "Los Angeles Kings"): "logos/tsdb/nhl/los-angeles-kings.png",
    ("NHL", "Minnesota Wild"): "logos/tsdb/nhl/minnesota-wild.png",
    ("NHL", "Montreal Canadiens"): "logos/tsdb/nhl/montreal-canadiens.png",
    ("NHL", "Nashville Predators"): "logos/tsdb/nhl/nashville-predators.png",
    ("NHL", "New Jersey Devils"): "logos/tsdb/nhl/new-jersey-devils.png",
    ("NHL", "New York Islanders"): "logos/tsdb/nhl/new-york-islanders.png",
    ("NHL", "New York Rangers"): "logos/tsdb/nhl/new-york-rangers.png",
    ("NHL", "Ottawa Senators"): "logos/tsdb/nhl/ottawa-senators.png",
    ("NHL", "Philadelphia Flyers"): "logos/tsdb/nhl/philadelphia-flyers.png",
    ("NHL", "Pittsburgh Penguins"): "logos/tsdb/nhl/pittsburgh-penguins.png",
    ("NHL", "San Jose Sharks"): "logos/tsdb/nhl/san-jose-sharks.png",
    ("NHL", "Seattle Kraken"): "logos/tsdb/nhl/seattle-kraken.png",
    ("NHL", "St. Louis Blues"): "logos/tsdb/nhl/st-louis-blues.png",
    ("NHL", "Tampa Bay Lightning"): "logos/tsdb/nhl/tampa-bay-lightning.png",
    ("NHL", "Toronto Maple Leafs"): "logos/tsdb/nhl/toronto-maple-leafs.png",
    ("NHL", "Utah Mammoth"): "logos/tsdb/nhl/utah-mammoth.png",
    ("NHL", "Vancouver Canucks"): "logos/tsdb/nhl/vancouver-canucks.png",
    ("NHL", "Vegas Golden Knights"): "logos/tsdb/nhl/vegas-golden-knights.png",
    ("NHL", "Washington Capitals"): "logos/tsdb/nhl/washington-capitals.png",
    ("NHL", "Winnipeg Jets"): "logos/tsdb/nhl/winnipeg-jets.png",

    # Premier League

    ("Soccer", "Arsenal"): "logos/tsdb/PL/arsenal.png",
    ("Soccer", "AFC Bournemouth"): "logos/tsdb/PL/bournemouth.png",
    ("Soccer", "Aston Villa"): "logos/tsdb/PL/aston-villa.png",
    ("Soccer", "Brentford"): "logos/tsdb/PL/brentford.png",
    ("Soccer", "Brighton & Hove Albion"): "logos/tsdb/PL/brighton.png",
    ("Soccer", "Chelsea"): "logos/tsdb/PL/chelsea.png",
    ("Soccer", "Coventry City"): "logos/tsdb/PL/coventry-city.png",
    ("Soccer", "Crystal Palace"): "logos/tsdb/PL/crystal-palace.png",
    ("Soccer", "Everton"): "logos/tsdb/PL/everton.png",
    ("Soccer", "Fulham"): "logos/tsdb/PL/fulham.png",
    ("Soccer", "Hull City"): "logos/tsdb/PL/hull-city.png",
    ("Soccer", "Ipswich Town"): "logos/tsdb/PL/ipswich-town.png",
    ("Soccer", "Leeds United"): "logos/tsdb/PL/leeds-united.png",
    ("Soccer", "Liverpool"): "logos/tsdb/PL/liverpool.png",
    ("Soccer", "Manchester City"): "logos/tsdb/PL/manchester-city.png",
    ("Soccer", "Manchester United"): "logos/tsdb/PL/manchester-united.png",
    ("Soccer", "Newcastle United"): "logos/tsdb/PL/newcastle-united.png",
    ("Soccer", "Nottingham Forest"): "logos/tsdb/PL/nottingham-forest.png",
    ("Soccer", "Sunderland"): "logos/tsdb/PL/sunderland.png",
    ("Soccer", "Tottenham Hotspur"): "logos/tsdb/PL/tottenham-hotspur.png",

    # La Liga

    ("Soccer", "Athletic Club"): "logos/tsdb/laliga/athletic-club.png",
    ("Soccer", "Atletico Madrid"): "logos/tsdb/laliga/atletico-madrid.png",
    ("Soccer", "Osasuna"): "logos/tsdb/laliga/osasuna.png",
    ("Soccer", "Celta Vigo"): "logos/tsdb/laliga/celta-vigo.png",
    ("Soccer", "Deportivo Alaves"): "logos/tsdb/laliga/alaves.png",
    ("Soccer", "Elche CF"): "logos/tsdb/laliga/elche.png",
    ("Soccer", "FC Barcelona"): "logos/tsdb/laliga/barcelona.png",
    ("Soccer", "Getafe CF"): "logos/tsdb/laliga/getafe.png",
    ("Soccer", "Levante"): "logos/tsdb/laliga/levante.png",
    ("Soccer", "Málaga"): "logos/tsdb/laliga/malaga.png",
    ("Soccer", "Racing Santander"): "logos/tsdb/laliga/racing-santander.png",
    ("Soccer", "Rayo Vallecano"): "logos/tsdb/laliga/rayo-vallecano.png",
    ("Soccer", "Deportivo"): "logos/tsdb/laliga/deportivo.png",
    ("Soccer", "Espanyol"): "logos/tsdb/laliga/espanyol.png",
    ("Soccer", "Real Betis"): "logos/tsdb/laliga/real-betis.png",
    ("Soccer", "Real Madrid"): "logos/tsdb/laliga/real-madrid.png",
    ("Soccer", "Real Sociedad"): "logos/tsdb/laliga/real-sociedad.png",
    ("Soccer", "Sevilla"): "logos/tsdb/laliga/sevilla.png",
    ("Soccer", "Valencia"): "logos/tsdb/laliga/valencia.png",
    ("Soccer", "Villarreal CF"): "logos/tsdb/laliga/villarreal.png",



("NCAA", "Abilene Christian Wildcats"): "logos/tsdb/ncaa/abilene-christian-wildcats.png",
    ("NCAA", "Air Force Falcons"): "logos/tsdb/ncaa/air-force-falcons.png",
    ("NCAA", "Akron Zips"): "logos/tsdb/ncaa/akron-zips.png",
    ("NCAA", "Alabama A&M Bulldogs"): "logos/tsdb/ncaa/alabama-a-m-bulldogs.png",
    ("NCAA", "Alabama Crimson Tide"): "logos/tsdb/ncaa/alabama-crimson-tide.png",
    ("NCAA", "Alabama State Hornets"): "logos/tsdb/ncaa/alabama-state-hornets.png",
    ("NCAA", "Albany Great Danes"): "logos/tsdb/ncaa/albany-great-danes.png",
    ("NCAA", "Alcorn State Braves"): "logos/tsdb/ncaa/alcorn-state-braves.png",
    ("NCAA", "American"): "logos/tsdb/ncaa/american.png",
    ("NCAA", "American International Yellow Jackets"): "logos/tsdb/ncaa/american-international-yellow-jackets.png",
    ("NCAA", "App State Mountaineers"): "logos/tsdb/ncaa/app-state-mountaineers.png",
    ("NCAA", "Appalachian State Mountaineers"): "logos/tsdb/ncaa/appalachian-state-mountaineers.png",
    ("NCAA", "Arizona State Sun Devils"): "logos/tsdb/ncaa/arizona-state-sun-devils.png",
    ("NCAA", "Arizona Wildcats"): "logos/tsdb/ncaa/arizona-wildcats.png",
    ("NCAA", "Arkansas Razorbacks"): "logos/tsdb/ncaa/arkansas-razorbacks.png",
    ("NCAA", "Arkansas State Red Wolves"): "logos/tsdb/ncaa/arkansas-state-red-wolves.png",
    ("NCAA", "Army Black Knights"): "logos/tsdb/ncaa/army-black-knights.png",
    ("NCAA", "Auburn Tigers"): "logos/tsdb/ncaa/auburn-tigers.png",
    ("NCAA", "Austin Peay Governors"): "logos/tsdb/ncaa/austin-peay-governors.png",
    ("NCAA", "BYU Cougars"): "logos/tsdb/ncaa/byu-cougars.png",
    ("NCAA", "Ball State Cardinals"): "logos/tsdb/ncaa/ball-state-cardinals.png",
    ("NCAA", "Baylor Bears"): "logos/tsdb/ncaa/baylor-bears.png",
    ("NCAA", "Boise State Broncos"): "logos/tsdb/ncaa/boise-state-broncos.png",
    ("NCAA", "Boston College Eagles"): "logos/tsdb/ncaa/boston-college-eagles.png",
    ("NCAA", "Bowling Green Falcons"): "logos/tsdb/ncaa/bowling-green-falcons.png",
    ("NCAA", "Bryant Bulldogs"): "logos/tsdb/ncaa/bryant-bulldogs.png",
    ("NCAA", "Bucknell Bison"): "logos/tsdb/ncaa/bucknell-bison.png",
    ("NCAA", "Buffalo Bulls"): "logos/tsdb/ncaa/buffalo-bulls.png",
    ("NCAA", "Butler Bulldogs"): "logos/tsdb/ncaa/butler-bulldogs.png",
    ("NCAA", "CS-Northridge Matadors"): "logos/tsdb/ncaa/cs-northridge-matadors.png",
    ("NCAA", "CSU Northridge Matadors"): "logos/tsdb/ncaa/csu-northridge-matadors.png",
    ("NCAA", "Cal Poly Mustangs"): "logos/tsdb/ncaa/cal-poly-mustangs.png",
    ("NCAA", "California Golden Bears"): "logos/tsdb/ncaa/california-golden-bears.png",
    ("NCAA", "Campbell Camels"): "logos/tsdb/ncaa/campbell-camels.png",
    ("NCAA", "Campbell Fighting Camels"): "logos/tsdb/ncaa/campbell-fighting-camels.png",
    ("NCAA", "Central Arkansas Bears"): "logos/tsdb/ncaa/central-arkansas-bears.png",
    ("NCAA", "Central Connecticut Blue Devils"): "logos/tsdb/ncaa/central-connecticut-blue-devils.png",
    ("NCAA", "Central Michigan Chippewas"): "logos/tsdb/ncaa/central-michigan-chippewas.png",
    ("NCAA", "Charleston (WV) Golden Eagles"): "logos/tsdb/ncaa/charleston-wv-golden-eagles.png",
    ("NCAA", "Charleston Southern Buccaneers"): "logos/tsdb/ncaa/charleston-southern-buccaneers.png",
    ("NCAA", "Charlotte 49ers"): "logos/tsdb/ncaa/charlotte-49ers.png",
    ("NCAA", "Chattanooga Mocs"): "logos/tsdb/ncaa/chattanooga-mocs.png",
    ("NCAA", "Cincinnati Bearcats"): "logos/tsdb/ncaa/cincinnati-bearcats.png",
    ("NCAA", "Citadel Bulldogs"): "logos/tsdb/ncaa/citadel-bulldogs.png",
    ("NCAA", "Clemson Tigers"): "logos/tsdb/ncaa/clemson-tigers.png",
    ("NCAA", "Coastal Carolina Chanticleers"): "logos/tsdb/ncaa/coastal-carolina-chanticleers.png",
    ("NCAA", "Colgate Raiders"): "logos/tsdb/ncaa/colgate-raiders.png",
    ("NCAA", "Colorado Buffaloes"): "logos/tsdb/ncaa/colorado-buffaloes.png",
    ("NCAA", "Colorado State Rams"): "logos/tsdb/ncaa/colorado-state-rams.png",
    ("NCAA", "Connecticut Huskies"): "logos/tsdb/ncaa/connecticut-huskies.png",
    ("NCAA", "Cornell Big Red"): "logos/tsdb/ncaa/cornell-big-red.png",
    ("NCAA", "Davidson Wildcats"): "logos/tsdb/ncaa/davidson-wildcats.png",
    ("NCAA", "Dayton Flyers"): "logos/tsdb/ncaa/dayton-flyers.png",
    ("NCAA", "Delaware Blue Hens"): "logos/tsdb/ncaa/delaware-blue-hens.png",
    ("NCAA", "Delaware State Hornets"): "logos/tsdb/ncaa/delaware-state-hornets.png",
    ("NCAA", "Dixie State Trailblazers"): "logos/tsdb/ncaa/dixie-state-trailblazers.png",
    ("NCAA", "Drake Bulldogs"): "logos/tsdb/ncaa/drake-bulldogs.png",
    ("NCAA", "Duke Blue Devils"): "logos/tsdb/ncaa/duke-blue-devils.png",
    ("NCAA", "Duquesne Dukes"): "logos/tsdb/ncaa/duquesne-dukes.png",
    ("NCAA", "East Carolina Pirates"): "logos/tsdb/ncaa/east-carolina-pirates.png",
    ("NCAA", "East Tenn. St. Buccaneers"): "logos/tsdb/ncaa/east-tenn-st-buccaneers.png",
    ("NCAA", "East Tennessee St. Buccaneers"): "logos/tsdb/ncaa/east-tennessee-st-buccaneers.png",
    ("NCAA", "East Tennessee State Buccaneers"): "logos/tsdb/ncaa/east-tennessee-state-buccaneers.png",
    ("NCAA", "Eastern Illinois Panthers"): "logos/tsdb/ncaa/eastern-illinois-panthers.png",
    ("NCAA", "Eastern Kentucky Colonels"): "logos/tsdb/ncaa/eastern-kentucky-colonels.png",
    ("NCAA", "Eastern Michigan Eagles"): "logos/tsdb/ncaa/eastern-michigan-eagles.png",
    ("NCAA", "Eastern Washington Eagles"): "logos/tsdb/ncaa/eastern-washington-eagles.png",
    ("NCAA", "Edward Waters Tigers"): "logos/tsdb/ncaa/edward-waters-tigers.png",
    ("NCAA", "Elon Phoenix"): "logos/tsdb/ncaa/elon-phoenix.png",
    ("NCAA", "Ferris State Bulldogs"): "logos/tsdb/ncaa/ferris-state-bulldogs.png",
    ("NCAA", "Florida A&M Rattlers"): "logos/tsdb/ncaa/florida-a-m-rattlers.png",
    ("NCAA", "Florida Atlantic Owls"): "logos/tsdb/ncaa/florida-atlantic-owls.png",
    ("NCAA", "Florida Gators"): "logos/tsdb/ncaa/florida-gators.png",
    ("NCAA", "Florida International Panthers"): "logos/tsdb/ncaa/florida-international-panthers.png",
    ("NCAA", "Florida Intl Golden Panthers"): "logos/tsdb/ncaa/florida-intl-golden-panthers.png",
    ("NCAA", "Florida State Seminoles"): "logos/tsdb/ncaa/florida-state-seminoles.png",
    ("NCAA", "Fordham Rams"): "logos/tsdb/ncaa/fordham-rams.png",
    ("NCAA", "Fresno State Bulldogs"): "logos/tsdb/ncaa/fresno-state-bulldogs.png",
    ("NCAA", "Furman Paladins"): "logos/tsdb/ncaa/furman-paladins.png",
    ("NCAA", "Georgetown Hoyas"): "logos/tsdb/ncaa/georgetown-hoyas.png",
    ("NCAA", "Georgia Bulldogs"): "logos/tsdb/ncaa/georgia-bulldogs.png",
    ("NCAA", "Georgia Southern Eagles"): "logos/tsdb/ncaa/georgia-southern-eagles.png",
    ("NCAA", "Georgia State Panthers"): "logos/tsdb/ncaa/georgia-state-panthers.png",
    ("NCAA", "Georgia Tech Yellow Jackets"): "logos/tsdb/ncaa/georgia-tech-yellow-jackets.png",
    ("NCAA", "Grambling State Tigers"): "logos/tsdb/ncaa/grambling-state-tigers.png",
    ("NCAA", "Grambling Tigers"): "logos/tsdb/ncaa/grambling-tigers.png",
    ("NCAA", "Hampton Pirates"): "logos/tsdb/ncaa/hampton-pirates.png",
    ("NCAA", "Hawai'i Rainbow Warriors"): "logos/tsdb/ncaa/hawaii-rainbow-warriors.png",
    ("NCAA", "Hawaii Warriors"): "logos/tsdb/ncaa/hawaii-warriors.png",
    ("NCAA", "Hofstra Pride"): "logos/tsdb/ncaa/hofstra-pride.png",
    ("NCAA", "Holy Cross Crusaders"): "logos/tsdb/ncaa/holy-cross-crusaders.png",
    ("NCAA", "Houston Baptist Huskies"): "logos/tsdb/ncaa/houston-baptist-huskies.png",
    ("NCAA", "Houston Christian Huskies"): "logos/tsdb/ncaa/houston-christian-huskies.png",
    ("NCAA", "Houston Cougars"): "logos/tsdb/ncaa/houston-cougars.png",
    ("NCAA", "Howard Bison"): "logos/tsdb/ncaa/howard-bison.png",
    ("NCAA", "Idaho State Bengals"): "logos/tsdb/ncaa/idaho-state-bengals.png",
    ("NCAA", "Idaho Vandals"): "logos/tsdb/ncaa/idaho-vandals.png",
    ("NCAA", "Illinois Fighting Illini"): "logos/tsdb/ncaa/illinois-fighting-illini.png",
    ("NCAA", "Illinois State Redbirds"): "logos/tsdb/ncaa/illinois-state-redbirds.png",
    ("NCAA", "Incarnate Word Cardinals"): "logos/tsdb/ncaa/incarnate-word-cardinals.png",
    ("NCAA", "Indiana Hoosiers"): "logos/tsdb/ncaa/indiana-hoosiers.png",
    ("NCAA", "Indiana State Sycamores"): "logos/tsdb/ncaa/indiana-state-sycamores.png",
    ("NCAA", "Iowa Hawkeyes"): "logos/tsdb/ncaa/iowa-hawkeyes.png",
    ("NCAA", "Iowa State Cyclones"): "logos/tsdb/ncaa/iowa-state-cyclones.png",
    ("NCAA", "Jackson State Tigers"): "logos/tsdb/ncaa/jackson-state-tigers.png",
    ("NCAA", "Jacksonville Dolphins"): "logos/tsdb/ncaa/jacksonville-dolphins.png",
    ("NCAA", "Jacksonville State Gamecocks"): "logos/tsdb/ncaa/jacksonville-state-gamecocks.png",
    ("NCAA", "James Madison Dukes"): "logos/tsdb/ncaa/james-madison-dukes.png",
    ("NCAA", "Johnson C Smith Golden Bulls"): "logos/tsdb/ncaa/johnson-c-smith-golden-bulls.png",
    ("NCAA", "Kansas Jayhawks"): "logos/tsdb/ncaa/kansas-jayhawks.png",
    ("NCAA", "Kansas State Wildcats"): "logos/tsdb/ncaa/kansas-state-wildcats.png",
    ("NCAA", "Kennesaw State Owls"): "logos/tsdb/ncaa/kennesaw-state-owls.png",
    ("NCAA", "Kent State Golden Flashes"): "logos/tsdb/ncaa/kent-state-golden-flashes.png",
    ("NCAA", "Kentucky Wildcats"): "logos/tsdb/ncaa/kentucky-wildcats.png",
    ("NCAA", "LSU Tigers"): "logos/tsdb/ncaa/lsu-tigers.png",
    ("NCAA", "Lafayette Leopards"): "logos/tsdb/ncaa/lafayette-leopards.png",
    ("NCAA", "Lamar Cardinals"): "logos/tsdb/ncaa/lamar-cardinals.png",
    ("NCAA", "Lehigh Mountain Hawks"): "logos/tsdb/ncaa/lehigh-mountain-hawks.png",
    ("NCAA", "Liberty Flames"): "logos/tsdb/ncaa/liberty-flames.png",
    ("NCAA", "Lincoln (CA) Oaklanders"): "logos/tsdb/ncaa/lincoln-ca-oaklanders.png",
    ("NCAA", "Lincoln (MO) Blue Tigers"): "logos/tsdb/ncaa/lincoln-mo-blue-tigers.png",
    ("NCAA", "Lindenwood Lions"): "logos/tsdb/ncaa/lindenwood-lions.png",
    ("NCAA", "Long Island University Sharks"): "logos/tsdb/ncaa/long-island-university-sharks.png",
    ("NCAA", "Louisiana Monroe Warhawks"): "logos/tsdb/ncaa/louisiana-monroe-warhawks.png",
    ("NCAA", "Louisiana Ragin' Cajuns"): "logos/tsdb/ncaa/louisiana-ragin-cajuns.png",
    ("NCAA", "Louisiana Tech Bulldogs"): "logos/tsdb/ncaa/louisiana-tech-bulldogs.png",
    ("NCAA", "Louisiana-Monroe Warhawks"): "logos/tsdb/ncaa/louisiana-monroe-warhawks.png",
    ("NCAA", "Louisville Cardinals"): "logos/tsdb/ncaa/louisville-cardinals.png",
    ("NCAA", "Maine Black Bears"): "logos/tsdb/ncaa/maine-black-bears.png",
    ("NCAA", "Marist Red Foxes"): "logos/tsdb/ncaa/marist-red-foxes.png",
    ("NCAA", "Marshall Thundering Herd"): "logos/tsdb/ncaa/marshall-thundering-herd.png",
    ("NCAA", "Maryland Terrapins"): "logos/tsdb/ncaa/maryland-terrapins.png",
    ("NCAA", "Massachusetts Minutemen"): "logos/tsdb/ncaa/massachusetts-minutemen.png",
    ("NCAA", "McNeese Cowboys"): "logos/tsdb/ncaa/mcneese-cowboys.png",
    ("NCAA", "McNeese State Cowboys"): "logos/tsdb/ncaa/mcneese-state-cowboys.png",
    ("NCAA", "Memphis Tigers"): "logos/tsdb/ncaa/memphis-tigers.png",
    ("NCAA", "Mercer Bears"): "logos/tsdb/ncaa/mercer-bears.png",
    ("NCAA", "Mercyhurst Lakers"): "logos/tsdb/ncaa/mercyhurst-lakers.png",
    ("NCAA", "Merrimack Warriors"): "logos/tsdb/ncaa/merrimack-warriors.png",
    ("NCAA", "Miami (OH) RedHawks"): "logos/tsdb/ncaa/miami-oh-redhawks.png",
    ("NCAA", "Miami Hurricanes"): "logos/tsdb/ncaa/miami-hurricanes.png",
    ("NCAA", "Michigan State Spartans"): "logos/tsdb/ncaa/michigan-state-spartans.png",
    ("NCAA", "Michigan Wolverines"): "logos/tsdb/ncaa/michigan-wolverines.png",
    ("NCAA", "Middle Tennessee Blue Raiders"): "logos/tsdb/ncaa/middle-tennessee-blue-raiders.png",
    ("NCAA", "Minnesota Golden Gophers"): "logos/tsdb/ncaa/minnesota-golden-gophers.png",
    ("NCAA", "Mississippi State Bulldogs"): "logos/tsdb/ncaa/mississippi-state-bulldogs.png",
    ("NCAA", "Mississippi Valley State Delta Devils"): "logos/tsdb/ncaa/mississippi-valley-state-delta-devils.png",
    ("NCAA", "Missouri S&T Miners"): "logos/tsdb/ncaa/missouri-s-t-miners.png",
    ("NCAA", "Missouri State Bears"): "logos/tsdb/ncaa/missouri-state-bears.png",
    ("NCAA", "Missouri Tigers"): "logos/tsdb/ncaa/missouri-tigers.png",
    ("NCAA", "Monmouth Hawks"): "logos/tsdb/ncaa/monmouth-hawks.png",
    ("NCAA", "Montana Grizzlies"): "logos/tsdb/ncaa/montana-grizzlies.png",
    ("NCAA", "Montana State Bobcats"): "logos/tsdb/ncaa/montana-state-bobcats.png",
    ("NCAA", "Morehead State Eagles"): "logos/tsdb/ncaa/morehead-state-eagles.png",
    ("NCAA", "Morgan State Bears"): "logos/tsdb/ncaa/morgan-state-bears.png",
    ("NCAA", "Murray State Racers"): "logos/tsdb/ncaa/murray-state-racers.png",
    ("NCAA", "NC State Wolfpack"): "logos/tsdb/ncaa/nc-state-wolfpack.png",
    ("NCAA", "NORTH FLORIDA STARS"): "logos/tsdb/ncaa/north-florida-stars.png",
    ("NCAA", "Navy Midshipmen"): "logos/tsdb/ncaa/navy-midshipmen.png",
    ("NCAA", "Nebraska Cornhuskers"): "logos/tsdb/ncaa/nebraska-cornhuskers.png",
    ("NCAA", "Nevada Wolf Pack"): "logos/tsdb/ncaa/nevada-wolf-pack.png",
    ("NCAA", "New Hampshire Wildcats"): "logos/tsdb/ncaa/new-hampshire-wildcats.png",
    ("NCAA", "New Mexico Lobos"): "logos/tsdb/ncaa/new-mexico-lobos.png",
    ("NCAA", "New Mexico State Aggies"): "logos/tsdb/ncaa/new-mexico-state-aggies.png",
    ("NCAA", "Nicholls State Colonels"): "logos/tsdb/ncaa/nicholls-state-colonels.png",
    ("NCAA", "Norfolk State Spartans"): "logos/tsdb/ncaa/norfolk-state-spartans.png",
    ("NCAA", "North Alabama Lions"): "logos/tsdb/ncaa/north-alabama-lions.png",
    ("NCAA", "North Carolina A&T Aggies"): "logos/tsdb/ncaa/north-carolina-a-t-aggies.png",
    ("NCAA", "North Carolina Central Eagles"): "logos/tsdb/ncaa/north-carolina-central-eagles.png",
    ("NCAA", "North Carolina Tar Heels"): "logos/tsdb/ncaa/north-carolina-tar-heels.png",
    ("NCAA", "North Dakota"): "logos/tsdb/ncaa/north-dakota.png",
    ("NCAA", "North Dakota Fighting Hawks"): "logos/tsdb/ncaa/north-dakota-fighting-hawks.png",
    ("NCAA", "North Dakota State Bison"): "logos/tsdb/ncaa/north-dakota-state-bison.png",
    ("NCAA", "North Greenville Crusaders"): "logos/tsdb/ncaa/north-greenville-crusaders.png",
    ("NCAA", "North Texas Mean Green"): "logos/tsdb/ncaa/north-texas-mean-green.png",
    ("NCAA", "Northeastern Huskies"): "logos/tsdb/ncaa/northeastern-huskies.png",
    ("NCAA", "Northern Arizona Lumberjacks"): "logos/tsdb/ncaa/northern-arizona-lumberjacks.png",
    ("NCAA", "Northern Colorado Bears"): "logos/tsdb/ncaa/northern-colorado-bears.png",
    ("NCAA", "Northern Illinois Huskies"): "logos/tsdb/ncaa/northern-illinois-huskies.png",
    ("NCAA", "Northern Iowa Panthers"): "logos/tsdb/ncaa/northern-iowa-panthers.png",
    ("NCAA", "Northwestern State Demons"): "logos/tsdb/ncaa/northwestern-state-demons.png",
    ("NCAA", "Northwestern Wildcats"): "logos/tsdb/ncaa/northwestern-wildcats.png",
    ("NCAA", "Notre Dame Fighting Irish"): "logos/tsdb/ncaa/notre-dame-fighting-irish.png",
    ("NCAA", "Ohio Bobcats"): "logos/tsdb/ncaa/ohio-bobcats.png",
    ("NCAA", "Ohio State Buckeyes"): "logos/tsdb/ncaa/ohio-state-buckeyes.png",
    ("NCAA", "Oklahoma Sooners"): "logos/tsdb/ncaa/oklahoma-sooners.png",
    ("NCAA", "Oklahoma State Cowboys"): "logos/tsdb/ncaa/oklahoma-state-cowboys.png",
    ("NCAA", "Old Dominion Monarchs"): "logos/tsdb/ncaa/old-dominion-monarchs.png",
    ("NCAA", "Ole Miss Rebels"): "logos/tsdb/ncaa/ole-miss-rebels.png",
    ("NCAA", "Oregon Ducks"): "logos/tsdb/ncaa/oregon-ducks.png",
    ("NCAA", "Oregon State Beavers"): "logos/tsdb/ncaa/oregon-state-beavers.png",
    ("NCAA", "Penn State Nittany Lions"): "logos/tsdb/ncaa/penn-state-nittany-lions.png",
    ("NCAA", "Pittsburgh Panthers"): "logos/tsdb/ncaa/pittsburgh-panthers.png",
    ("NCAA", "Portland State Vikings"): "logos/tsdb/ncaa/portland-state-vikings.png",
    ("NCAA", "Prairie View A&M Panthers"): "logos/tsdb/ncaa/prairie-view-a-m-panthers.png",
    ("NCAA", "Prairie View Panthers"): "logos/tsdb/ncaa/prairie-view-panthers.png",
    ("NCAA", "Purdue Boilermakers"): "logos/tsdb/ncaa/purdue-boilermakers.png",
    ("NCAA", "Rhode Island Rams"): "logos/tsdb/ncaa/rhode-island-rams.png",
    ("NCAA", "Rice Owls"): "logos/tsdb/ncaa/rice-owls.png",
    ("NCAA", "Richmond Spiders"): "logos/tsdb/ncaa/richmond-spiders.png",
    ("NCAA", "Robert Morris Colonials"): "logos/tsdb/ncaa/robert-morris-colonials.png",
    ("NCAA", "Rutgers Scarlet Knights"): "logos/tsdb/ncaa/rutgers-scarlet-knights.png",
    ("NCAA", "SE Louisiana Lions"): "logos/tsdb/ncaa/se-louisiana-lions.png",
    ("NCAA", "SMU Mustangs"): "logos/tsdb/ncaa/smu-mustangs.png",
    ("NCAA", "SOUTH FLORIDA STARS"): "logos/tsdb/ncaa/south-florida-stars.png",
    ("NCAA", "Sacramento State Hornets"): "logos/tsdb/ncaa/sacramento-state-hornets.png",
    ("NCAA", "Sacred Heart Pioneers"): "logos/tsdb/ncaa/sacred-heart-pioneers.png",
    ("NCAA", "Saint Francis Red Flash"): "logos/tsdb/ncaa/saint-francis-red-flash.png",
    ("NCAA", "Sam Houston Bearkats"): "logos/tsdb/ncaa/sam-houston-bearkats.png",
    ("NCAA", "Sam Houston State Bearkats"): "logos/tsdb/ncaa/sam-houston-state-bearkats.png",
    ("NCAA", "Samford Bulldogs"): "logos/tsdb/ncaa/samford-bulldogs.png",
    ("NCAA", "San Diego State Aztecs"): "logos/tsdb/ncaa/san-diego-state-aztecs.png",
    ("NCAA", "San Diego Toreros"): "logos/tsdb/ncaa/san-diego-toreros.png",
    ("NCAA", "San Jose State Spartans"): "logos/tsdb/ncaa/san-jose-state-spartans.png",
    ("NCAA", "San José St Spartans"): "logos/tsdb/ncaa/san-jos-st-spartans.png",
    ("NCAA", "San José State Spartans"): "logos/tsdb/ncaa/san-jos-state-spartans.png",
    ("NCAA", "Savannah State Tigers"): "logos/tsdb/ncaa/savannah-state-tigers.png",
    ("NCAA", "South Alabama Jaguars"): "logos/tsdb/ncaa/south-alabama-jaguars.png",
    ("NCAA", "South Carolina Gamecocks"): "logos/tsdb/ncaa/south-carolina-gamecocks.png",
    ("NCAA", "South Carolina State Bulldogs"): "logos/tsdb/ncaa/south-carolina-state-bulldogs.png",
    ("NCAA", "South Dakota Coyotes"): "logos/tsdb/ncaa/south-dakota-coyotes.png",
    ("NCAA", "South Dakota State Jackrabbits"): "logos/tsdb/ncaa/south-dakota-state-jackrabbits.png",
    ("NCAA", "South Florida Bulls"): "logos/tsdb/ncaa/south-florida-bulls.png",
    ("NCAA", "Southeast Missouri State Redhawks"): "logos/tsdb/ncaa/southeast-missouri-state-redhawks.png",
    ("NCAA", "Southeastern Louisiana Lions"): "logos/tsdb/ncaa/southeastern-louisiana-lions.png",
    ("NCAA", "Southern Illinois Salukis"): "logos/tsdb/ncaa/southern-illinois-salukis.png",
    ("NCAA", "Southern Jaguars"): "logos/tsdb/ncaa/southern-jaguars.png",
    ("NCAA", "Southern Methodist Mustangs"): "logos/tsdb/ncaa/southern-methodist-mustangs.png",
    ("NCAA", "Southern Miss Golden Eagles"): "logos/tsdb/ncaa/southern-miss-golden-eagles.png",
    ("NCAA", "Southern Mississippi Golden Eagles"): "logos/tsdb/ncaa/southern-mississippi-golden-eagles.png",
    ("NCAA", "Southern Utah Thunderbirds"): "logos/tsdb/ncaa/southern-utah-thunderbirds.png",
    ("NCAA", "St Francis (PA) Red Flash"): "logos/tsdb/ncaa/st-francis-pa-red-flash.png",
    ("NCAA", "St. Francis (IL) Fighting Saints"): "logos/tsdb/ncaa/st-francis-il-fighting-saints.png",
    ("NCAA", "St. Francis (PA) Red Flash"): "logos/tsdb/ncaa/st-francis-pa-red-flash.png",
    ("NCAA", "St. Joseph's (IN) Pumas"): "logos/tsdb/ncaa/st-josephs-in-pumas.png",
    ("NCAA", "St. Mary's (CA) Gaels"): "logos/tsdb/ncaa/st-marys-ca-gaels.png",
    ("NCAA", "St. Paul's College Tigers"): "logos/tsdb/ncaa/st-pauls-college-tigers.png",
    ("NCAA", "St. Peter's Peacocks"): "logos/tsdb/ncaa/st-peters-peacocks.png",
    ("NCAA", "Stanford Cardinal"): "logos/tsdb/ncaa/stanford-cardinal.png",
    ("NCAA", "Stephen F Austin Lumberjacks"): "logos/tsdb/ncaa/stephen-f-austin-lumberjacks.png",
    ("NCAA", "Stephen F. Austin Lumberjacks"): "logos/tsdb/ncaa/stephen-f-austin-lumberjacks.png",
    ("NCAA", "Stonehill Skyhawks"): "logos/tsdb/ncaa/stonehill-skyhawks.png",
    ("NCAA", "Stony Brook Seawolves"): "logos/tsdb/ncaa/stony-brook-seawolves.png",
    ("NCAA", "Syracuse Orange"): "logos/tsdb/ncaa/syracuse-orange.png",
    ("NCAA", "TCU Horned Frogs"): "logos/tsdb/ncaa/tcu-horned-frogs.png",
    ("NCAA", "Tarleton State Texans"): "logos/tsdb/ncaa/tarleton-state-texans.png",
    ("NCAA", "Temple Owls"): "logos/tsdb/ncaa/temple-owls.png",
    ("NCAA", "Tennessee State Tigers"): "logos/tsdb/ncaa/tennessee-state-tigers.png",
    ("NCAA", "Tennessee Tech Golden Eagles"): "logos/tsdb/ncaa/tennessee-tech-golden-eagles.png",
    ("NCAA", "Tennessee Volunteers"): "logos/tsdb/ncaa/tennessee-volunteers.png",
    ("NCAA", "Texas A&M Aggies"): "logos/tsdb/ncaa/texas-a-m-aggies.png",
    ("NCAA", "Texas Longhorns"): "logos/tsdb/ncaa/texas-longhorns.png",
    ("NCAA", "Texas Southern Tigers"): "logos/tsdb/ncaa/texas-southern-tigers.png",
    ("NCAA", "Texas State Bobcats"): "logos/tsdb/ncaa/texas-state-bobcats.png",
    ("NCAA", "Texas Tech Red Raiders"): "logos/tsdb/ncaa/texas-tech-red-raiders.png",
    ("NCAA", "Toledo Rockets"): "logos/tsdb/ncaa/toledo-rockets.png",
    ("NCAA", "Towson Tigers"): "logos/tsdb/ncaa/towson-tigers.png",
    ("NCAA", "Troy Trojans"): "logos/tsdb/ncaa/troy-trojans.png",
    ("NCAA", "Tulane Green Wave"): "logos/tsdb/ncaa/tulane-green-wave.png",
    ("NCAA", "Tulsa Golden Hurricane"): "logos/tsdb/ncaa/tulsa-golden-hurricane.png",
    ("NCAA", "UAB Blazers"): "logos/tsdb/ncaa/uab-blazers.png",
    ("NCAA", "UAlbany Great Danes"): "logos/tsdb/ncaa/ualbany-great-danes.png",
    ("NCAA", "UC Davis Aggies"): "logos/tsdb/ncaa/uc-davis-aggies.png",
    ("NCAA", "UCF Knights"): "logos/tsdb/ncaa/ucf-knights.png",
    ("NCAA", "UCLA Bruins"): "logos/tsdb/ncaa/ucla-bruins.png",
    ("NCAA", "UConn Huskies"): "logos/tsdb/ncaa/uconn-huskies.png",
    ("NCAA", "UL Monroe Warhawks"): "logos/tsdb/ncaa/ul-monroe-warhawks.png",
    ("NCAA", "UNLV Rebels"): "logos/tsdb/ncaa/unlv-rebels.png",
    ("NCAA", "USC Trojans"): "logos/tsdb/ncaa/usc-trojans.png",
    ("NCAA", "UT Martin Skyhawks"): "logos/tsdb/ncaa/ut-martin-skyhawks.png",
    ("NCAA", "UT San Antonio Roadrunners"): "logos/tsdb/ncaa/ut-san-antonio-roadrunners.png",
    ("NCAA", "UTEP Miners"): "logos/tsdb/ncaa/utep-miners.png",
    ("NCAA", "UTSA Roadrunners"): "logos/tsdb/ncaa/utsa-roadrunners.png",
    ("NCAA", "Utah State Aggies"): "logos/tsdb/ncaa/utah-state-aggies.png",
    ("NCAA", "Utah Tech Trailblazers"): "logos/tsdb/ncaa/utah-tech-trailblazers.png",
    ("NCAA", "Utah Utes"): "logos/tsdb/ncaa/utah-utes.png",
    ("NCAA", "VMI Keydets"): "logos/tsdb/ncaa/vmi-keydets.png",
    ("NCAA", "Valparaiso Crusaders"): "logos/tsdb/ncaa/valparaiso-crusaders.png",
    ("NCAA", "Vanderbilt Commodores"): "logos/tsdb/ncaa/vanderbilt-commodores.png",
    ("NCAA", "Villanova Wildcats"): "logos/tsdb/ncaa/villanova-wildcats.png",
    ("NCAA", "Virginia Cavaliers"): "logos/tsdb/ncaa/virginia-cavaliers.png",
    ("NCAA", "Virginia Tech Hokies"): "logos/tsdb/ncaa/virginia-tech-hokies.png",
    ("NCAA", "WV Wesleyan Bobcats"): "logos/tsdb/ncaa/wv-wesleyan-bobcats.png",
    ("NCAA", "Wagner Seahawks"): "logos/tsdb/ncaa/wagner-seahawks.png",
    ("NCAA", "Wake Forest Demon Deacons"): "logos/tsdb/ncaa/wake-forest-demon-deacons.png",
    ("NCAA", "Washington Huskies"): "logos/tsdb/ncaa/washington-huskies.png",
    ("NCAA", "Washington State Cougars"): "logos/tsdb/ncaa/washington-state-cougars.png",
    ("NCAA", "Weber State Wildcats"): "logos/tsdb/ncaa/weber-state-wildcats.png",
    ("NCAA", "West Chester Golden Rams"): "logos/tsdb/ncaa/west-chester-golden-rams.png",
    ("NCAA", "West Georgia Wolves"): "logos/tsdb/ncaa/west-georgia-wolves.png",
    ("NCAA", "West Virginia Mountaineers"): "logos/tsdb/ncaa/west-virginia-mountaineers.png",
    ("NCAA", "West Virginia Tech Golden Bears"): "logos/tsdb/ncaa/west-virginia-tech-golden-bears.png",
    ("NCAA", "Western Carolina Catamounts"): "logos/tsdb/ncaa/western-carolina-catamounts.png",
    ("NCAA", "Western Illinois Leathernecks"): "logos/tsdb/ncaa/western-illinois-leathernecks.png",
    ("NCAA", "Western Kentucky Hilltoppers"): "logos/tsdb/ncaa/western-kentucky-hilltoppers.png",
    ("NCAA", "Western Michigan Broncos"): "logos/tsdb/ncaa/western-michigan-broncos.png",
    ("NCAA", "Western New Mexico Mustangs"): "logos/tsdb/ncaa/western-new-mexico-mustangs.png",
    ("NCAA", "William & Mary Tribe"): "logos/tsdb/ncaa/william-mary-tribe.png",
    ("NCAA", "Wisconsin Badgers"): "logos/tsdb/ncaa/wisconsin-badgers.png",
    ("NCAA", "Wofford Terriers"): "logos/tsdb/ncaa/wofford-terriers.png",
    ("NCAA", "Wyoming Cowboys"): "logos/tsdb/ncaa/wyoming-cowboys.png",
    ("NCAA", "Yale Bulldogs"): "logos/tsdb/ncaa/yale-bulldogs.png",
    ("NCAA", "Youngstown State Penguins"): "logos/tsdb/ncaa/youngstown-state-penguins.png",

}