TEAM_LOGOS = {
    ("MLB", "Arizona Diamondbacks"): "logos/tsdb/mlb/arizona-diamondbacks.png",
    ("MLB", "Athletics"): "logos/tsdb/mlb/athletics.png",
    ("MLB", "Atlanta Braves"): "logos/tsdb/mlb/atlanta-braves.png",
    ("MLB", "Baltimore Orioles"): "logos/tsdb/mlb/baltimore-orioles.png",
    ("MLB", "Boston Red Sox"): "logos/tsdb/mlb/boston-red-sox.png",
    ("MLB", "Chicago Cubs"): "logos/tsdb/mlb/chicago-cubs.png",
    ("MLB", "Chicago White Sox"): "logos/tsdb/mlb/chicago-white-sox.png",
    ("MLB", "Cincinnati Reds"): "logos/tsdb/mlb/cincinnati-reds.png",
    ("MLB", "Cleveland Guardians"): "logos/tsdb/mlb/cleveland-guardians.png",
    ("MLB", "Colorado Rockies"): "logos/tsdb/mlb/colorado-rockies.png",
    ("MLB", "Detroit Tigers"): "logos/tsdb/mlb/detroit-tigers.png",
    ("MLB", "Houston Astros"): "logos/tsdb/mlb/houston-astros.png",
    ("MLB", "Kansas City Royals"): "logos/tsdb/mlb/kansas-city-royals.png",
    ("MLB", "Los Angeles Angels"): "logos/tsdb/mlb/los-angeles-angels.png",
    ("MLB", "Los Angeles Dodgers"): "logos/tsdb/mlb/los-angeles-dodgers.png",
    ("MLB", "Miami Marlins"): "logos/tsdb/mlb/miami-marlins.png",
    ("MLB", "Milwaukee Brewers"): "logos/tsdb/mlb/milwaukee-brewers.png",
    ("MLB", "Minnesota Twins"): "logos/tsdb/mlb/minnesota-twins.png",
    ("MLB", "New York Mets"): "logos/tsdb/mlb/new-york-mets.png",
    ("MLB", "New York Yankees"): "logos/tsdb/mlb/new-york-yankees.png",
    ("MLB", "Philadelphia Phillies"): "logos/tsdb/mlb/philadelphia-phillies.png",
    ("MLB", "Pittsburgh Pirates"): "logos/tsdb/mlb/pittsburgh-pirates.png",
    ("MLB", "San Diego Padres"): "logos/tsdb/mlb/san-diego-padres.png",
    ("MLB", "San Francisco Giants"): "logos/tsdb/mlb/san-francisco-giants.png",
    ("MLB", "Seattle Mariners"): "logos/tsdb/mlb/seattle-mariners.png",
    ("MLB", "St. Louis Cardinals"): "logos/tsdb/mlb/st-louis-cardinals.png",
    ("MLB", "Tampa Bay Rays"): "logos/tsdb/mlb/tampa-bay-rays.png",
    ("MLB", "Texas Rangers"): "logos/tsdb/mlb/texas-rangers.png",
    ("MLB", "Toronto Blue Jays"): "logos/tsdb/mlb/toronto-blue-jays.png",
    ("MLB", "Washington Nationals"): "logos/tsdb/mlb/washington-nationals.png",


("NBA", "Atlanta Hawks"): "logos/tsdb/nba/atlanta-hawks.png",
("NBA", "Boston Celtics"): "logos/tsdb/nba/boston-celtics.png",
("NBA", "Brooklyn Nets"): "logos/tsdb/nba/brooklyn-nets.png",
("NBA", "Charlotte Hornets"): "logos/tsdb/nba/charlotte-hornets.png",
("NBA", "Chicago Bulls"): "logos/tsdb/nba/chicago-bulls.png",
("NBA", "Cleveland Cavaliers"): "logos/tsdb/nba/cleveland-cavaliers.png",
("NBA", "Dallas Mavericks"): "logos/tsdb/nba/dallas-mavericks.png",
("NBA", "Denver Nuggets"): "logos/tsdb/nba/denver-nuggets.png",
("NBA", "Detroit Pistons"): "logos/tsdb/nba/detroit-pistons.png",
("NBA", "Golden State Warriors"): "logos/tsdb/nba/golden-state-warriors.png",
("NBA", "Houston Rockets"): "logos/tsdb/nba/houston-rockets.png",
("NBA", "Indiana Pacers"): "logos/tsdb/nba/indiana-pacers.png",
("NBA", "Los Angeles Clippers"): "logos/tsdb/nba/los-angeles-clippers.png",
("NBA", "Los Angeles Lakers"): "logos/tsdb/nba/los-angeles-lakers.png",
("NBA", "Memphis Grizzlies"): "logos/tsdb/nba/memphis-grizzlies.png",
("NBA", "Miami Heat"): "logos/tsdb/nba/miami-heat.png",
("NBA", "Milwaukee Bucks"): "logos/tsdb/nba/milwaukee-bucks.png",
("NBA", "Minnesota Timberwolves"): "logos/tsdb/nba/minnesota-timberwolves.png",
("NBA", "New Orleans Pelicans"): "logos/tsdb/nba/new-orleans-pelicans.png",
("NBA", "New York Knicks"): "logos/tsdb/nba/new-york-knicks.png",
("NBA", "Oklahoma City Thunder"): "logos/tsdb/nba/oklahoma-city-thunder.png",
("NBA", "Orlando Magic"): "logos/tsdb/nba/orlando-magic.png",
("NBA", "Philadelphia 76ers"): "logos/tsdb/nba/philadelphia-76ers.png",
("NBA", "Phoenix Suns"): "logos/tsdb/nba/phoenix-suns.png",
("NBA", "Portland Trail Blazers"): "logos/tsdb/nba/portland-trail-blazers.png",
("NBA", "Sacramento Kings"): "logos/tsdb/nba/sacramento-kings.png",
("NBA", "San Antonio Spurs"): "logos/tsdb/nba/san-antonio-spurs.png",
("NBA", "Toronto Raptors"): "logos/tsdb/nba/toronto-raptors.png",
("NBA", "Utah Jazz"): "logos/tsdb/nba/utah-jazz.png",
("NBA", "Washington Wizards"): "logos/tsdb/nba/washington-wizards.png",


("NFL", "Arizona Cardinals"): "logos/tsdb/nfl/arizona-cardinals.png",
    ("NFL", "Atlanta Falcons"): "logos/tsdb/nfl/atlanta-falcons.png",
    ("NFL", "Baltimore Ravens"): "logos/tsdb/nfl/baltimore-ravens.png",
    ("NFL", "Buffalo Bills"): "logos/tsdb/nfl/buffalo-bills.png",
    ("NFL", "Carolina Panthers"): "logos/tsdb/nfl/carolina-panthers.png",
    ("NFL", "Chicago Bears"): "logos/tsdb/nfl/chicago-bears.png",
    ("NFL", "Cincinnati Bengals"): "logos/tsdb/nfl/cincinnati-bengals.png",
    ("NFL", "Cleveland Browns"): "logos/tsdb/nfl/cleveland-browns.png",
    ("NFL", "Dallas Cowboys"): "logos/tsdb/nfl/dallas-cowboys.png",
    ("NFL", "Denver Broncos"): "logos/tsdb/nfl/denver-broncos.png",
    ("NFL", "Detroit Lions"): "logos/tsdb/nfl/detroit-lions.png",
    ("NFL", "Green Bay Packers"): "logos/tsdb/nfl/green-bay-packers.png",
    ("NFL", "Houston Texans"): "logos/tsdb/nfl/houston-texans.png",
    ("NFL", "Indianapolis Colts"): "logos/tsdb/nfl/indianapolis-colts.png",
    ("NFL", "Jacksonville Jaguars"): "logos/tsdb/nfl/jacksonville-jaguars.png",
    ("NFL", "Kansas City Chiefs"): "logos/tsdb/nfl/kansas-city-chiefs.png",
    ("NFL", "Las Vegas Raiders"): "logos/tsdb/nfl/las-vegas-raiders.png",
    ("NFL", "Los Angeles Chargers"): "logos/tsdb/nfl/los-angeles-chargers.png",
    ("NFL", "Los Angeles Rams"): "logos/tsdb/nfl/los-angeles-rams.png",
    ("NFL", "Miami Dolphins"): "logos/tsdb/nfl/miami-dolphins.png",
    ("NFL", "Minnesota Vikings"): "logos/tsdb/nfl/minnesota-vikings.png",
    ("NFL", "New England Patriots"): "logos/tsdb/nfl/new-england-patriots.png",
    ("NFL", "New Orleans Saints"): "logos/tsdb/nfl/new-orleans-saints.png",
    ("NFL", "New York Giants"): "logos/tsdb/nfl/new-york-giants.png",
    ("NFL", "New York Jets"): "logos/tsdb/nfl/new-york-jets.png",
    ("NFL", "Philadelphia Eagles"): "logos/tsdb/nfl/philadelphia-eagles.png",
    ("NFL", "Pittsburgh Steelers"): "logos/tsdb/nfl/pittsburgh-steelers.png",
    ("NFL", "San Francisco 49ers"): "logos/tsdb/nfl/san-francisco-49ers.png",
    ("NFL", "Seattle Seahawks"): "logos/tsdb/nfl/seattle-seahawks.png",
    ("NFL", "Tampa Bay Buccaneers"): "logos/tsdb/nfl/tampa-bay-buccaneers.png",
    ("NFL", "Tennessee Titans"): "logos/tsdb/nfl/tennessee-titans.png",
    ("NFL", "Washington Commanders"): "logos/tsdb/nfl/washington-commanders.png",

    ("NFL", "ARI"): "logos/tsdb/nfl/arizona-cardinals.png",
    ("NFL", "ATL"): "logos/tsdb/nfl/atlanta-falcons.png",
    ("NFL", "BAL"): "logos/tsdb/nfl/baltimore-ravens.png",
    ("NFL", "BUF"): "logos/tsdb/nfl/buffalo-bills.png",
    ("NFL", "CAR"): "logos/tsdb/nfl/carolina-panthers.png",
    ("NFL", "CHI"): "logos/tsdb/nfl/chicago-bears.png",
    ("NFL", "CIN"): "logos/tsdb/nfl/cincinnati-bengals.png",
    ("NFL", "CLE"): "logos/tsdb/nfl/cleveland-browns.png",
    ("NFL", "DAL"): "logos/tsdb/nfl/dallas-cowboys.png",
    ("NFL", "DEN"): "logos/tsdb/nfl/denver-broncos.png",
    ("NFL", "DET"): "logos/tsdb/nfl/detroit-lions.png",
    ("NFL", "GB"): "logos/tsdb/nfl/green-bay-packers.png",
    ("NFL", "HOU"): "logos/tsdb/nfl/houston-texans.png",
    ("NFL", "IND"): "logos/tsdb/nfl/indianapolis-colts.png",
    ("NFL", "JAX"): "logos/tsdb/nfl/jacksonville-jaguars.png",
    ("NFL", "KC"): "logos/tsdb/nfl/kansas-city-chiefs.png",
    ("NFL", "LV"): "logos/tsdb/nfl/las-vegas-raiders.png",
    ("NFL", "LAC"): "logos/tsdb/nfl/los-angeles-chargers.png",
    ("NFL", "LAR"): "logos/tsdb/nfl/los-angeles-rams.png",
    ("NFL", "MIA"): "logos/tsdb/nfl/miami-dolphins.png",
    ("NFL", "MIN"): "logos/tsdb/nfl/minnesota-vikings.png",
    ("NFL", "NE"): "logos/tsdb/nfl/new-england-patriots.png",
    ("NFL", "NO"): "logos/tsdb/nfl/new-orleans-saints.png",
    ("NFL", "NYG"): "logos/tsdb/nfl/new-york-giants.png",
    ("NFL", "NYJ"): "logos/tsdb/nfl/new-york-jets.png",
    ("NFL", "PHI"): "logos/tsdb/nfl/philadelphia-eagles.png",
    ("NFL", "PIT"): "logos/tsdb/nfl/pittsburgh-steelers.png",
    ("NFL", "SF"): "logos/tsdb/nfl/san-francisco-49ers.png",
    ("NFL", "SEA"): "logos/tsdb/nfl/seattle-seahawks.png",
    ("NFL", "TB"): "logos/tsdb/nfl/tampa-bay-buccaneers.png",
    ("NFL", "TEN"): "logos/tsdb/nfl/tennessee-titans.png",
    ("NFL", "WAS"): "logos/tsdb/nfl/washington-commanders.png",

("WNBA", "Atlanta Dream"): "logos/wnba/atlanta-dream.svg",
("WNBA", "Chicago Sky"): "logos/wnba/chicago-sky.svg",
("WNBA", "Connecticut Sun"): "logos/wnba/connecticut-sun.svg",
("WNBA", "Dallas Wings"): "logos/wnba/dallas-wings.svg",
("WNBA", "Golden State Valkyries"): "logos/wnba/golden-state-valkyries.svg",
("WNBA", "Indiana Fever"): "logos/wnba/indiana-fever.svg",
("WNBA", "Las Vegas Aces"): "logos/wnba/las-vegas-aces.svg",
("WNBA", "Los Angeles Sparks"): "logos/wnba/los-angeles-sparks.svg",
("WNBA", "Minnesota Lynx"): "logos/wnba/minnesota-lynx.svg",
("WNBA", "New York Liberty"): "logos/wnba/new-york-liberty.svg",
("WNBA", "Phoenix Mercury"): "logos/wnba/phoenix-mercury.svg",
("WNBA", "Seattle Storm"): "logos/wnba/seattle-storm.svg",
("WNBA", "Washington Mystics"): "logos/wnba/washington-mystics.svg",

    # NHL

    ("NHL", "Anaheim Ducks"): "logos/tsdb/nhl/anaheim-ducks.png",
    ("NHL", "Boston Bruins"): "logos/tsdb/nhl/boston-bruins.png",
    ("NHL", "Buffalo Sabres"): "logos/tsdb/nhl/buffalo-sabres.png",
    ("NHL", "Calgary Flames"): "logos/tsdb/nhl/calgary-flames.png",
    ("NHL", "Carolina Hurricanes"): "logos/tsdb/nhl/carolina-hurricanes.png",
    ("NHL", "Chicago Blackhawks"): "logos/tsdb/nhl/chicago-blackhawks.png",
    ("NHL", "Colorado Avalanche"): "logos/tsdb/nhl/colorado-avalanche.png",
    ("NHL", "Columbus Blue Jackets"): "logos/tsdb/nhl/columbus-blue-jackets.png",
    ("NHL", "Dallas Stars"): "logos/tsdb/nhl/dallas-stars.png",
    ("NHL", "Detroit Red Wings"): "logos/tsdb/nhl/detroit-red-wings.png",
    ("NHL", "Edmonton Oilers"): "logos/tsdb/nhl/edmonton-oilers.png",
    ("NHL", "Florida Panthers"): "logos/tsdb/nhl/florida-panthers.png",
    ("NHL", "Los Angeles Kings"): "logos/tsdb/nhl/los-angeles-kings.png",
    ("NHL", "Minnesota Wild"): "logos/tsdb/nhl/minnesota-wild.png",
    ("NHL", "Montreal Canadiens"): "logos/tsdb/nhl/montreal-canadiens.png",
    ("NHL", "Nashville Predators"): "logos/tsdb/nhl/nashville-predators.png",
    ("NHL", "New Jersey Devils"): "logos/tsdb/nhl/new-jersey-devils.png",
    ("NHL", "New York Islanders"): "logos/tsdb/nhl/new-york-islanders.png",
    ("NHL", "New York Rangers"): "logos/tsdb/nhl/new-york-rangers.png",
    ("NHL", "Ottawa Senators"): "logos/tsdb/nhl/ottawa-senators.png",
    ("NHL", "Philadelphia Flyers"): "logos/tsdb/nhl/philadelphia-flyers.png",
    ("NHL", "Pittsburgh Penguins"): "logos/tsdb/nhl/pittsburgh-penguins.png",
    ("NHL", "San Jose Sharks"): "logos/tsdb/nhl/san-jose-sharks.png",
    ("NHL", "Seattle Kraken"): "logos/tsdb/nhl/seattle-kraken.png",
    ("NHL", "St. Louis Blues"): "logos/tsdb/nhl/st-louis-blues.png",
    ("NHL", "Tampa Bay Lightning"): "logos/tsdb/nhl/tampa-bay-lightning.png",
    ("NHL", "Toronto Maple Leafs"): "logos/tsdb/nhl/toronto-maple-leafs.png",
    ("NHL", "Utah Mammoth"): "logos/tsdb/nhl/utah-mammoth.png",
    ("NHL", "Vancouver Canucks"): "logos/tsdb/nhl/vancouver-canucks.png",
    ("NHL", "Vegas Golden Knights"): "logos/tsdb/nhl/vegas-golden-knights.png",
    ("NHL", "Washington Capitals"): "logos/tsdb/nhl/washington-capitals.png",
    ("NHL", "Winnipeg Jets"): "logos/tsdb/nhl/winnipeg-jets.png",
}

