TEAM_LOGOS = {
    ("MLB", "Arizona Diamondbacks"): "logos/mlb/arizona-diamondbacks.svg",
    ("MLB", "Athletics"): "logos/mlb/athletics.svg",
    ("MLB", "Atlanta Braves"): "logos/mlb/atlanta-braves.svg",
    ("MLB", "Baltimore Orioles"): "logos/mlb/baltimore-orioles.svg",
    ("MLB", "Boston Red Sox"): "logos/mlb/boston-red-sox.svg",
    ("MLB", "Chicago Cubs"): "logos/mlb/chicago-cubs.svg",
    ("MLB", "Chicago White Sox"): "logos/mlb/chicago-white-sox.svg",
    ("MLB", "Cincinnati Reds"): "logos/mlb/cincinnati-reds.svg",
    ("MLB", "Cleveland Guardians"): "logos/mlb/cleveland-guardians.svg",
    ("MLB", "Colorado Rockies"): "logos/mlb/colorado-rockies.svg",
    ("MLB", "Detroit Tigers"): "logos/mlb/detroit-tigers.svg",
    ("MLB", "Houston Astros"): "logos/mlb/houston-astros.svg",
    ("MLB", "Kansas City Royals"): "logos/mlb/kansas-city-royals.svg",
    ("MLB", "Los Angeles Angels"): "logos/mlb/los-angeles-angels.svg",
    ("MLB", "Los Angeles Dodgers"): "logos/mlb/los-angeles-dodgers.svg",
    ("MLB", "Miami Marlins"): "logos/mlb/miami-marlins.svg",
    ("MLB", "Milwaukee Brewers"): "logos/mlb/milwaukee-brewers.svg",
    ("MLB", "Minnesota Twins"): "logos/mlb/minnesota-twins.svg",
    ("MLB", "New York Mets"): "logos/mlb/new-york-mets.svg",
    ("MLB", "New York Yankees"): "logos/mlb/new-york-yankees.svg",
    ("MLB", "Philadelphia Phillies"): "logos/mlb/philadelphia-phillies.svg",
    ("MLB", "Pittsburgh Pirates"): "logos/mlb/pittsburgh-pirates.svg",
    ("MLB", "San Diego Padres"): "logos/mlb/san-diego-padres.svg",
    ("MLB", "San Francisco Giants"): "logos/mlb/san-francisco-giants.svg",
    ("MLB", "Seattle Mariners"): "logos/mlb/seattle-mariners.svg",
    ("MLB", "St. Louis Cardinals"): "logos/mlb/st-louis-cardinals.svg",
    ("MLB", "Tampa Bay Rays"): "logos/mlb/tampa-bay-rays.svg",
    ("MLB", "Texas Rangers"): "logos/mlb/texas-rangers.svg",
    ("MLB", "Toronto Blue Jays"): "logos/mlb/toronto-blue-jays.svg",
    ("MLB", "Washington Nationals"): "logos/mlb/washington-nationals.svg",


("NBA", "Atlanta Hawks"): "logos/nba/atlanta-hawks.svg",
("NBA", "Boston Celtics"): "logos/nba/boston-celtics.svg",
("NBA", "Brooklyn Nets"): "logos/nba/brooklyn-nets.svg",
("NBA", "Charlotte Hornets"): "logos/nba/charlotte-hornets.svg",
("NBA", "Chicago Bulls"): "logos/nba/chicago-bulls.svg",
("NBA", "Cleveland Cavaliers"): "logos/nba/cleveland-cavaliers.svg",
("NBA", "Dallas Mavericks"): "logos/nba/dallas-mavericks.svg",
("NBA", "Denver Nuggets"): "logos/nba/denver-nuggets.svg",
("NBA", "Detroit Pistons"): "logos/nba/detroit-pistons.svg",
("NBA", "Golden State Warriors"): "logos/nba/golden-state-warriors.svg",
("NBA", "Houston Rockets"): "logos/nba/houston-rockets.svg",
("NBA", "Indiana Pacers"): "logos/nba/indiana-pacers.svg",
("NBA", "Los Angeles Clippers"): "logos/nba/los-angeles-clippers.svg",
("NBA", "Los Angeles Lakers"): "logos/nba/los-angeles-lakers.svg",
("NBA", "Memphis Grizzlies"): "logos/nba/memphis-grizzlies.svg",
("NBA", "Miami Heat"): "logos/nba/miami-heat.svg",
("NBA", "Milwaukee Bucks"): "logos/nba/milwaukee-bucks.svg",
("NBA", "Minnesota Timberwolves"): "logos/nba/minnesota-timberwolves.svg",
("NBA", "New Orleans Pelicans"): "logos/nba/new-orleans-pelicans.svg",
("NBA", "New York Knicks"): "logos/nba/new-york-knicks.svg",
("NBA", "Oklahoma City Thunder"): "logos/nba/oklahoma-city-thunder.svg",
("NBA", "Orlando Magic"): "logos/nba/orlando-magic.svg",
("NBA", "Philadelphia 76ers"): "logos/nba/philadelphia-76ers.svg",
("NBA", "Phoenix Suns"): "logos/nba/phoenix-suns.svg",
("NBA", "Portland Trail Blazers"): "logos/nba/portland-trail-blazers.svg",
("NBA", "Sacramento Kings"): "logos/nba/sacramento-kings.svg",
("NBA", "San Antonio Spurs"): "logos/nba/san-antonio-spurs.svg",
("NBA", "Toronto Raptors"): "logos/nba/toronto-raptors.svg",
("NBA", "Utah Jazz"): "logos/nba/utah-jazz.svg",
("NBA", "Washington Wizards"): "logos/nba/washington-wizards.svg",


("NFL", "Arizona Cardinals"): "logos/nfl/arizona-cardinals.png",
    ("NFL", "Atlanta Falcons"): "logos/nfl/atlanta-falcons.png",
    ("NFL", "Baltimore Ravens"): "logos/nfl/baltimore-ravens.png",
    ("NFL", "Buffalo Bills"): "logos/nfl/buffalo-bills.png",
    ("NFL", "Carolina Panthers"): "logos/nfl/carolina-panthers.png",
    ("NFL", "Chicago Bears"): "logos/nfl/chicago-bears.png",
    ("NFL", "Cincinnati Bengals"): "logos/nfl/cincinnati-bengals.png",
    ("NFL", "Cleveland Browns"): "logos/nfl/cleveland-browns.png",
    ("NFL", "Dallas Cowboys"): "logos/nfl/dallas-cowboys.png",
    ("NFL", "Denver Broncos"): "logos/nfl/denver-broncos.png",
    ("NFL", "Detroit Lions"): "logos/nfl/detroit-lions.png",
    ("NFL", "Green Bay Packers"): "logos/nfl/green-bay-packers.png",
    ("NFL", "Houston Texans"): "logos/nfl/houston-texans.png",
    ("NFL", "Indianapolis Colts"): "logos/nfl/indianapolis-colts.png",
    ("NFL", "Jacksonville Jaguars"): "logos/nfl/jacksonville-jaguars.png",
    ("NFL", "Kansas City Chiefs"): "logos/nfl/kansas-city-chiefs.png",
    ("NFL", "Las Vegas Raiders"): "logos/nfl/las-vegas-raiders.png",
    ("NFL", "Los Angeles Chargers"): "logos/nfl/los-angeles-chargers.png",
    ("NFL", "Los Angeles Rams"): "logos/nfl/los-angeles-rams.png",
    ("NFL", "Miami Dolphins"): "logos/nfl/miami-dolphins.png",
    ("NFL", "Minnesota Vikings"): "logos/nfl/minnesota-vikings.png",
    ("NFL", "New England Patriots"): "logos/nfl/new-england-patriots.png",
    ("NFL", "New Orleans Saints"): "logos/nfl/new-orleans-saints.png",
    ("NFL", "New York Giants"): "logos/nfl/new-york-giants.png",
    ("NFL", "New York Jets"): "logos/nfl/new-york-jets.png",
    ("NFL", "Philadelphia Eagles"): "logos/nfl/philadelphia-eagles.png",
    ("NFL", "Pittsburgh Steelers"): "logos/nfl/pittsburgh-steelers.png",
    ("NFL", "San Francisco 49ers"): "logos/nfl/san-francisco-49ers.png",
    ("NFL", "Seattle Seahawks"): "logos/nfl/seattle-seahawks.png",
    ("NFL", "Tampa Bay Buccaneers"): "logos/nfl/tampa-bay-buccaneers.png",
    ("NFL", "Tennessee Titans"): "logos/nfl/tennessee-titans.png",
    ("NFL", "Washington Commanders"): "logos/nfl/washington-commanders.png",

    ("NFL", "ARI"): "logos/nfl/arizona-cardinals.png",
    ("NFL", "ATL"): "logos/nfl/atlanta-falcons.png",
    ("NFL", "BAL"): "logos/nfl/baltimore-ravens.png",
    ("NFL", "BUF"): "logos/nfl/buffalo-bills.png",
    ("NFL", "CAR"): "logos/nfl/carolina-panthers.png",
    ("NFL", "CHI"): "logos/nfl/chicago-bears.png",
    ("NFL", "CIN"): "logos/nfl/cincinnati-bengals.png",
    ("NFL", "CLE"): "logos/nfl/cleveland-browns.png",
    ("NFL", "DAL"): "logos/nfl/dallas-cowboys.png",
    ("NFL", "DEN"): "logos/nfl/denver-broncos.png",
    ("NFL", "DET"): "logos/nfl/detroit-lions.png",
    ("NFL", "GB"): "logos/nfl/green-bay-packers.png",
    ("NFL", "HOU"): "logos/nfl/houston-texans.png",
    ("NFL", "IND"): "logos/nfl/indianapolis-colts.png",
    ("NFL", "JAX"): "logos/nfl/jacksonville-jaguars.png",
    ("NFL", "KC"): "logos/nfl/kansas-city-chiefs.png",
    ("NFL", "LV"): "logos/nfl/las-vegas-raiders.png",
    ("NFL", "LAC"): "logos/nfl/los-angeles-chargers.png",
    ("NFL", "LAR"): "logos/nfl/los-angeles-rams.png",
    ("NFL", "MIA"): "logos/nfl/miami-dolphins.png",
    ("NFL", "MIN"): "logos/nfl/minnesota-vikings.png",
    ("NFL", "NE"): "logos/nfl/new-england-patriots.png",
    ("NFL", "NO"): "logos/nfl/new-orleans-saints.png",
    ("NFL", "NYG"): "logos/nfl/new-york-giants.png",
    ("NFL", "NYJ"): "logos/nfl/new-york-jets.png",
    ("NFL", "PHI"): "logos/nfl/philadelphia-eagles.png",
    ("NFL", "PIT"): "logos/nfl/pittsburgh-steelers.png",
    ("NFL", "SF"): "logos/nfl/san-francisco-49ers.png",
    ("NFL", "SEA"): "logos/nfl/seattle-seahawks.png",
    ("NFL", "TB"): "logos/nfl/tampa-bay-buccaneers.png",
    ("NFL", "TEN"): "logos/nfl/tennessee-titans.png",
    ("NFL", "WAS"): "logos/nfl/washington-commanders.png",

("WNBA", "Atlanta Dream"): "logos/wnba/atlanta-dream.svg",
("WNBA", "Chicago Sky"): "logos/wnba/chicago-sky.svg",
("WNBA", "Connecticut Sun"): "logos/wnba/connecticut-sun.svg",
("WNBA", "Dallas Wings"): "logos/wnba/dallas-wings.svg",
("WNBA", "Golden State Valkyries"): "logos/wnba/golden-state-valkyries.svg",
("WNBA", "Indiana Fever"): "logos/wnba/indiana-fever.svg",
("WNBA", "Las Vegas Aces"): "logos/wnba/las-vegas-aces.svg",
("WNBA", "Los Angeles Sparks"): "logos/wnba/los-angeles-sparks.svg",
("WNBA", "Minnesota Lynx"): "logos/wnba/minnesota-lynx.svg",
("WNBA", "New York Liberty"): "logos/wnba/new-york-liberty.svg",
("WNBA", "Phoenix Mercury"): "logos/wnba/phoenix-mercury.svg",
("WNBA", "Seattle Storm"): "logos/wnba/seattle-storm.svg",
("WNBA", "Washington Mystics"): "logos/wnba/washington-mystics.svg",
}

