# Generated by Django 6.0.7 on 2026-07-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=10)),
                ('season', models.IntegerField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('game_date', models.DateField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
    ]
