# Generated by Django 6.0.7 on 2026-07-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20),
            preserve_default=False,
        ),
    ]
