# Generated by Django 6.0.7 on 2026-07-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_game_game_id_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
