# Generated by Django 6.0.7 on 2026-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='experience_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='watch_type',
            field=models.CharField(blank=True, choices=[('LIVE', 'Attended Live'), ('TV', 'Watched Live on TV'), ('REPLAY', 'Watched Replay'), ('HIGHLIGHTS', 'Highlights Only')], max_length=10, null=True),
        ),
    ]
