# Generated by Django 6.0.7 on 2026-07-23 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_gamelog_experience_rating_gamelog_quality_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamelog',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_user_game_log'),
        ),
    ]
