# Generated by Django 6.0.7 on 2026-07-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.CharField(max_length=20),
        ),
    ]
