# Generated by Django 6.0.7 on 2026-07-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_game_competition_alter_game_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
