# Generated by Django 6.0.7 on 2026-08-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(max_length=40),
        ),
    ]
