# Generated by Django 6.0.7 on 2026-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
