# Generated by Django 6.0.7 on 2026-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_gamelog_watched_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='experience_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='quality_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
