# Generated by Django 6.0.7 on 2026-08-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_game_game_end_game_game_start_gamechatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_end',
        ),
    ]
