# Generated by Django 6.0.7 on 2026-08-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_remove_game_game_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
