# Generated by Django 6.0.7 on 2026-08-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_game_game_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='event_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='racing_series',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
