# Generated by Django 6.0.7 on 2026-09-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_game_event_name_game_racing_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='race_winner',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
