# Generated by Django 6.0.7 on 2026-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_game_race_winner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['game_date'], name='game_date_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['league', 'game_date'], name='league_date_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['league', 'competition', 'game_date'], name='league_comp_date_idx'),
        ),
    ]
